name: Build Windows x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2

      - name: Yarn Install
        run: yarn install

      - name: Make
        run: yarn make
      
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./out/make/**/**/*.exe

