name: Build Windows x64

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ['windows-latest','ubuntu-latest']

    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: bahmutov/npm-install@HEAD

      - name: Make
        run: yarn make
      
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./out/make 

